# PistonExploits Config
# This config will automatically update itself!
---
antibackdoor:
  # Both players and console won't be able to execute these commands.
  blockedcommands:
    - "op"
    - "ban"
    - "bukkit"
    - "minecraft"
antilag:
  entityremover:
    WITHER_SKULL: 25 # If there are more than 50 skulls they will be removed on chunk UNLOAD.
    WITHER: 20 # Withers can cause lag. Max 20 allowed at chunk UNLOAD.
  fluidstopper:
    worlds:
      normal: false
      nether: true
      end: false
    radius: 100 # If a person is out of this radius the fluid will stop flowing!
plugmanprotection: true # When activated hackers can't unload the plugin anymore. IT IS HIGHLY RECOMMENDED TO KEEP THIS ON!!!
discord:
  activated: false # Should we send discord messages
  url: https://discord.com/api/webhooks/xxx/xxx # The webhook to send messages to
  events:
    onceper: 5 # Messages can only be sent again after this minutes.
    lag:
      actvated: false
      ping: 12 # Under 12 tps you will get pinged in the discord!
      message: 14 # At this tps only a message will be sent!
    lagmachine:
      removal: true # When actions have been taken you will be pinged!