# PistonExploits Config
# This config will automatically update itself!
---
antibackdoor:
  # Both players and console won't be able to execute these commands.
  blockedcommands:
    - "op"
    - "ban"
    - "bukkit"
    - "minecraft"
plugmanprotection: true # When activated hackers can't unload the plugin anymore. IT IS HIGHLY RECOMMENDED TO KEEP THIS ON!!!
discord:
  activated: false # Should we send discord messages
  url: https://discord.com/api/webhooks/xxx/xxx # The webhook to send messages to