# PistonExploits Config
# This config will automatically update itself!
antibackdoor:
  blockedcommands:
    - "op"
    - "ban"
plugmanprotection: true # When activated hackers can't unload the plugin anymore. IT IS HIGHLY RECOMMENDED TO KEEP THIS ON!!!
discord:
  activated: false
  url: https://discord.com/api/webhooks/xxx/xxx